apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagflow-ui
spec:
  selector:
    matchLabels:
      app: dagflow-ui
  template:
    metadata:
      labels:
        app: dagflow-ui
    spec:
      containers:
      - name: dagflow-ui
        image: dagflow-react
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      # initContainers:
      # - name: init-mongodb
      #   image: appropriate/curl
      #   command: ["/bin/sh", "-c"]
      #   args:
      #     - until curl http://mongodb:27017; do echo waiting for mongodb; sleep 2; done;
      containers:
      - name: app
        image: dagflow-app-with-db-url
        imagePullPolicy: Never
        args:
          - "uvicorn"
          - "main:app"
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "8000"
        env:
          - name: AIRFLOW_UID
            value: "1000"
          - name: AIRFLOW_GID
            value: "0"
          - name: AIRFLOW_PROJ_DIR
            value: "./airflow"
          - name: AIRFLOW_VERSION
            value: "2.5.3"
          - name: PYTHON_VERSION
            value: "3.10"
          - name: DAGFLOW_MONGODB_URL
            value: "mongodb://mongodb-service:27017/"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: dags-volume
          mountPath: /dags
        # - name: app-volume
          # mountPath: /app
      volumes:
      - name: dags-volume
        hostPath:
          path: /home/jegath/Documents/intelops/sps/dagflow/airflow/dags
      # - name: app-volume
      #   hostPath:
      #     path: /home/jegath/Documents/intelops/sps/dagflow/app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data-volume
          mountPath: /data/db
      volumes:
      - name: mongodb-data-volume
        hostPath:
          path: /home/jegath/Documents/intelops/sps/dagflow/mongodb_data

---
apiVersion: v1
kind: Service
metadata:
  name: dagflow-ui-service
spec:
  selector:
    app: dagflow-ui
  ports:
  - protocol: TCP
    port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
