# Docker compose to start the fast api application
version: "3.8"

services:
  pyroscope:
    image: pyroscope/pyroscope
    # volumes:
      # - ./pyroscope-data:/var/lib/pyroscope
      # - ./pyroscope-config.yml:/etc/pyroscope/server.yml
    environment:
      - PYROSCOPE_LOG_LEVEL=debug
    ports:
      - '4040:4040'
    command:
      - 'server'

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - AIRFLOW_VERSION=${AIRFLOW_VERSION}
        - CUSTOM_PYTHON_VERSION=${PYTHON_VERSION}
    command: uvicorn main:app --host 0.0.00 --port 8000
    volumes:
      - ${AIRFLOW_PROJ_DIR}/dags:/dags
      # - /home/jegath/Documents/docker-airflow-2.1.4/dags:/dags
      - ./app:/app
    env_file:
      - .env
    # environment:
    #   - AIRFLOW_UID=1000
    #   - AIRFLOW_GID=0
    #   - AIRFLOW_PROJ_DIR=./airflow
    #   - AIRFLOW_VERSION=2.5.3
    #   - PYTHON_VERSION=3.10

    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  react:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    command: nginx -g 'daemon off;'